import { preload } from 'react-dom';
import images from '@/data/images.json';

/**
 * Responsive <picture> for images generated by `npm run images`.
 * Serves AVIF with a WebP fallback, picks the right width from `sizes`, and
 * lazy-loads unless `priority` is set (use that only for the first visible
 * hero image).
 *
 * <picture> is rendered with `display: contents`, so styles written for the
 * <img> (object-fit, sizing, hover effects) keep working unchanged.
 */
export default function Picture({
  name,
  alt,
  sizes = '100vw',
  priority = false,
  lazy = !priority,
  className,
  style,
  blur = true,
  ...rest
}) {
  const meta = images[name];
  if (!meta) throw new Error(`<Picture>: unknown image "${name}". Run \`npm run images\`.`);

  const base = `/media/${name}.${meta.hash}`;
  const srcSet = (ext) => meta.widths.map((w) => `${base}-${w}.${ext} ${w}w`).join(', ');
  const fallbackWidth = meta.widths.find((w) => w >= 640) ?? meta.widths.at(-1);

  if (priority) {
    preload(`${base}-${fallbackWidth}.avif`, {
      as: 'image',
      type: 'image/avif',
      imageSrcSet: srcSet('avif'),
      imageSizes: sizes,
      fetchPriority: 'high',
    });
  }

  const placeholder =
    blur && meta.blur
      ? { backgroundImage: `url("${meta.blur}")`, backgroundSize: 'cover', backgroundPosition: 'center' }
      : null;

  return (
    <picture style={{ display: 'contents' }}>
      <source type="image/avif" srcSet={srcSet('avif')} sizes={sizes} />
      <img
        src={`${base}-${fallbackWidth}.webp`}
        srcSet={srcSet('webp')}
        sizes={sizes}
        width={meta.w}
        height={meta.h}
        alt={alt}
        loading={lazy ? 'lazy' : 'eager'}
        fetchPriority={priority ? 'high' : undefined}
        decoding="async"
        className={className}
        style={placeholder ? { ...placeholder, ...style } : style}
        {...rest}
      />
    </picture>
  );
}
